# Navigation Links
#   To link a homepage widget, specify the URL as a hash `#` followed by the filename of the
#     desired widget in your `content/home/` folder.
#   The weight parameter defines the order that the links will appear in.

[[main]]
  name = "Home"
  url = "#about"
  weight = 10

#[[main]]
#  name = "Oportunidades"
#  url = "#opportunities"
#  weight = 10
  
  
[[main]]
  name = "Blog"
  url = "#posts"
  weight = 20
  
[[main]]
  name = "Projetos"
  url = "#projects"
  weight = 30

[[main]]
  name = "Publicações"
  url = "#publications"
  weight = 40

[[main]]
  name = "Cursos"
  url = "#"
  hasChildren = true
  weight = 50
  
[[main]]
  parent = "Cursos"
  name = "Ciência aberta e reproutível"
  url = "cursos/open_science/"
  weight = 10
  
[[main]]
  parent = "Cursos"
  name = "Análise de dados aplicada ao processo decisório"
  url = "cursos/dados_ppga/"
  weight = 30

[[main]]
  parent = "Cursos"
  name = "Introdução ao R"
  url = "cursos/intro_r/"
  weight = 20
  
[[main]]
  parent = "Cursos"
  name = "Sistemas de Suporte à Decisão Espacial"
  url = "cursos/spatial/"
  weight = 40
  
[[main]]
  parent = "Cursos"
  name = "Logística"
  url = "cursos/log_all/"
  weight = 50
  
#[[main]]
#  parent = "Cursos"
#  name = "Logística Urbana"
#  url = "cursos/log_urb/"
#  weight = 40
  
#[[main]]
#  parent = "Cursos"
#  name = "Urban Analytics"
#  url = "cursos/urban/"
#  weight = 50

[[main]]
  name = "Disciplinas"
  url = "#"
  hasChildren = true
  weight = 60
  
#[[main]]
#  parent = "Disciplinas"
#  name = "Logística - 2021/1"
#  url = "disciplinas/log/"
#  weight = 10

[[main]]
  parent = "Disciplinas"
  name = "Logística - Eng. Produção Civil - 2023/2"
  url = "disciplinas/log_epc/"
  weight = 10
  
[[main]]
  parent = "Disciplinas"
  name = "Logística - ADM - 2023/2"
  url = "disciplinas/log_adm/"
  weight = 20
 
[[main]]
  parent = "Disciplinas"
  name = "Ciência aberta e em colaboração - PPGA - 2023/2"
  url = "https://open-reproducible-research.github.io/website/"
  weight = 30
  
  
[[main]]
   parent = "Disciplinas"
   name = "Análise de dados aplicada ao processo decisório - PPGA - 2023/1"
   url = "disciplinas/dados_ppga/"
   weight = 35
  
#[[main]]
#  parent = "Disciplinas"
#  name = "Quarto: um novo sistema para publicação técnica e científica - PPGA - 2022/2"
#  url = "https://curso-quarto.netlify.app"
#  weight = 50

#[[main]]
#  parent = "Disciplinas"
#  name = "Introdução ao R - PPGA - 2022/2"
#  url = "disciplinas/r_pos_2022/"
#  weight = 40

#[[main]]
#  parent = "Disciplinas"
#  name = "Sistemas de Suporte à Decisão Espacial - PPGA - 2021/2"#  url = "disciplinas/sdss/"
#  weight = 50


  
#[[main]]
#  parent = "Disciplinas"
#  name = "Logística - ADM Especial - 2022/2"
#  url = "disciplinas/log_especial/"
#  weight = 30

#[[main]]
#  parent = "Disciplinas"
#  name = "Administração da produção - 2022/2"
#  url = "disciplinas/adm_prod/"
#  weight = 70
  
#[[main]]
#  parent = "Disciplinas"
#  name = "Análise de Dados para gestão organizacional - 2021/1"
#  url = "disciplinas/dados_grad/"
#  weight = 10

#[[main]]
#  parent = "Disciplinas"
#  name = "Análise de Dados aplicada ao processo decisório - 2020/2"
#  url = "courses/dados_pos/"
#  weight = 70
  

[[main]]
  name = "Contato"
  url = "#contact"
  weight = 90


# Link to a PDF of your resume/CV from the menu.
# To enable, copy your resume/CV to `static/files/cv.pdf` and uncomment the lines below.
[[main]]
    name = "CV"
    url = "files/cv.pdf"
    weight = 80

