---
date: "2020-12-275T00:00:00+01:00"
draft: false
menu:
  log_adm:
    parent: Atividades de aprendizagem
    weight: 5
title: 2. KPIs e nível de serviço
editor_options: 
  markdown: 
    wrap: 70
output: 
  blogdown::html_page:
    toc: true
type: docs
weight: 20
---

## Objetivo de aprendizagem: 

Consolidar conceitos estruturais como "Logística" e "Cadeia de suprimentos". 

## Pontos

5 pontos

## Grupos de trabalho
**Grupo 1**: Artur Abreu, Pedro Lemes, Arthur Joia e Gabriel Ramos

**Grupo 2**: Amanda Nascimento, Jancler Adrano, Lucas Gomes, Maria Júlia Alves e Naiara Caetano

**Grupo 3:** Amanda Evelyn, Aline Lacerda, Bárbara Silva e Isadora Oliveira

**Grupo 4:** Marina Caroline, Rayssa Aparecida, Thayna Assis e Yara Bertilie

**Grupo 5:** Arthus Ferraz, Mathias, Sebastião e Caroline

**Grupo 6:** Renata, Webert, Taynara e Leonardo


## Atividades

Cada grupo deverá elaborar um parágrafo com a sua própria definição de "nível de serviço logístico". 

Cada grupo fará uma pesquisa sobre os indicadores de desempenho/nível de serviço recebidos e fará a interpretacão do indicador, críticas, alinhamento com as atividades-chave da gestão da cadeia de suprimentos, classificação do indicador segundo informação. 


