---
date: "2020-12-275T00:00:00+01:00"
draft: false
menu:
  log_adm:
    parent: Atividades de aprendizagem
    weight: 55
title: 5. Gestão de estoques e armazenagem (em sala)
editor_options: 
  markdown: 
    wrap: 70
output: 
  blogdown::html_page:
    toc: true
type: docs
weight: 55
---



A Star Company fornece motores elétricos para a empresa Electronic Moon Inc. com base no preço de entrega. A Star tem a responsabilidade de fornecer o transporte. O Gerente de transportes tem três opções para o serviço de transporte. Ele reuniu as seguintes informações:

Modo de transporte	|Tempo em trânsito(dias)	|Frete (R$/unidade)	|Tamanho de carregamento (unidades)
---------|-----------|---------|-----------
Cabotagem |	21	|25|	1500
Ferroviário	|10	|40	|1000
Rodoviário	|4	|88	|500
 
A Electronic Moon Inc compra **4.800 unidades por ano** a um preço (com a entrega) contratado de **R$ 500 por unidade**. Os custos de manutenção de estoque para ambas as empresas são de **25% por ano**. 

Baseado nos custos logísticos totais anuais, que modo de transporte a Star Company deve escolher? 

> Dicas:   
1.	O custo de transporte deve ser anualizado, considerando o frete de cada unidade.  
2.	O estoque em trânsito refere-se à mercadoria que fica em estoque, mas em trânsito no sistema de transportes. Lembre-se que cada unidade da demanda anual é transportada e fica um % do ano em trânsito; e o custo de estoque incide sobre cada peça. Ainda, o custo de transporte refere-se ao frete a ser pago por cada unidade transportada no ano. Deve ser estimado consirando:    
   i.	Custo de manter estoque anual (lembre-se de considerar o custo de aquisição de cada motor e o % de custo de manutenção).  
   ii.	A proporção de tempo anualizado referente ao tempo em trânsito (TT/365).  
   iii.	Demanda anual.  
3.	O custo do estoque na fábrica de componentes considera o estoque médio (unidades no carregamento dividido por 2) e o custo de manutenção de cada item em estoque.     
4.	Pense no custo total = custo de manter estoque + custo de transporte.  

