---
date: "2021-06-30T00:00:00+01:00"
draft: true
menu:
  log_adm:
    parent: Atividades de aprendizagem
    weight: 15
title: 4. Gestão de transportes
editor_options: 
  markdown: 
    wrap: 70
output: 
  blogdown::html_page:
    toc: true
type: docs
weight: 45
---

Nesta atividade, os grupos deverão trabalhar com a contrução de conteúdos sobre as tecnologias de transporte (modos) e sobre o contexto de oferta desses modos no Brasil. 

Não será necessário preparar uma apresentação ou mesmo um relatório. Os grupos deverão organizar as informações e buscar instrumentos para ilustração a serem discutidos em sala.

Os grupos que trabalharão com a caracterização das tecnologias deverão explorar os seguintes elementos: 

a) subclassificação dos modos;   
b) Como os modos se originaram;   
c) Elementos de infra e superestrutura;   
d) Elementos de material rodante;   
e) Onde e como ocorrem os gargalos (pontos onde a capacidade é menor do que a demanda, gerando congestionamento)

Os grupos que trabalharão com a caracterização do contexto, deverão explorar os seguintes elementos: 

a) Uso no Brasil;
b) Como é a distribuição da infraestrutura no país;
c) Quem são os operadores desse modo;
d) Como o Brasil se compara com a distribuição de infraestrutura em outros países.

A discussão em sala acontecerá dia **17/10**. 
