---
date: "2022-05-09T00:00:00+01:00"
draft: true
menu:
  log_adm:
    parent: Projetos
    weight: 6
title: Projeto Integrador - Etapa 3
toc: true
type: docs
weight: 16
---

Fiquem à vontade para utilizar a ferramenta que o grupo escolher. O envio será feito pela atividade aberta no Paper Dropbox. Caso haja links, por favor, incluam no documento. O valor deste trabalho é **20 pontos**.

O prazo para conclusão desta atividade será dia **10/07**.

Os grupos de trabalho deverão: 

1. **Registrar** alguma situação onde atividades-chave da cadeia de suprimentos acontecem e apresentam inadequações relacionadas a uma às duas dimensões: (i) eficiência - relação entre consumo dos recursos e a produção; (ii) responsividade - nível de serviço.

2. **Descrever** *brevemente* o fluxo (usando a imaginação mesmo!) desde um determinado fornecedor primário, passando pelas etapas de manufatura e pelas de distribuição até a situação registrada. Indique possíveis atividades depois do que é apresentado como registro considerando a estrutura da cadeia de suprimentos. 

3. **Relacionar** possíveis causas e soluções ao problema retratado.

4. **Discutir** as externalidades da operação retratada e como poderiam ser mitigadas, sem comprometer o _trade-off_ entre eficiência e responsividade. 

Sejam completos e sucintos nas respostas! Ilustrem bem o processo. Recomendo que escolham um processo familiar, pois fica mais fácil inferir sobre fluxos, causas e soluções.
