---
date: "2023-05-085T00:00:00+01:00"
draft: false
menu:
  log_epc:
    parent: Atividades de aprendizagem
    weight: 4
title: 2. KPIs e nível de serviço (para quem não esteve presente)
editor_options: 
  markdown: 
    wrap: 70
output: 
  blogdown::html_page:
    toc: true
type: docs
weight: 25
---

**Prazo para entrega: 25/05/2023** - Entregar pela atividade no SIGAA - TRABALHO INDIVIDUAL


## Objetivo de aprendizagem: 

Consolidar conceitos estruturais como "Logística" e "Cadeia de suprimentos". 

## Pontos

10 pontos

## Atividades

Leia do artigo [Logística e Serviço ao Cliente: como Aumentar a satisfação do cliente através de uma cadeia de abastecimento eficaz](https://github.com/retaoliveira/relements/raw/main/texto/servico_log.pdf) e responda as perguntas que seguem. A atividade deverá ser submetida na tarefa no SIGAA.


## 1. Varejo tradicional em uma cadeia de suprimentos

a. Como um comerciante de alimentos (mercearia ou pequeno supermercado) poderia usar o inventário (produtos em estoque no estabelecimento) para aumentar a capacidade responsividade da cadeia de suprimentos da empresa? Quais as consequências dessa decisão?

## 2. Varejo e-commerce - serviço de entrega

a. Como uma empresa de entregas em domicílio pode utilizar os preços dos serviços de entrega para melhorar sua rentabilidade?
b. Quais cuidados devem ser observados?
c. Cite um indicador que você recomendaria para análise de desempenho logístico desse processo e um indicador para mensurar o nível de serviço percebido pelo cliente. 
