---
date: "2023-03-235T00:00:00+01:00"
draft: true
menu:
  log_epc:
    parent: Atividades de aprendizagem
    weight: 15
title: 4. Gestão de transportes 
editor_options: 
  markdown: 
    wrap: 70
output: 
  blogdown::html_page:
    toc: true
type: docs
weight: 15
---


Leia do artigo [O uso da tecnologia nas adversidades da gestão de transportes](E:/Google Drive/Meu Drive/02_work/01_disciplinas/2025_2/02_grad_logistica/logistica_graduacao/05_atividades_aprendizagem/05_atividades_aprendizagem/logistica_2022/TI/ti2013.pdf). Responda as questões a seguir:



1. Como as TICs podem contribuir para a mitigação dos impactos disruptivos (greve de caminhoneiros, pandemias, guerras) na gestão de transportes?

2. Discuta o **problema estrutural** brasileiro quanto ao **transporte de cargas** em escala regional que compromete o alinhamento estratégico na cadeia de suprimentos, a eficiência, a responsividade, a sustentabilidade, a resiliência e a competitividade de produtos brasileiros no mercado internacional.

3. Na sua opinião, faz sentido os caminhoneiros demandarem intervenção das autoridades públicas para imposição de uma tabela de fretes mínimos ao mercado? Justifique. 
