---
date: "2020-12-275T00:00:00+01:00"
draft: false
menu:
  log_epc:
    parent: Aulas
    weight: 10
title: 'Aula 01 - Introdução à disciplina'
editor_options: 
  markdown: 
    wrap: 70
output: 
  blogdown::html_page:
    toc: true
type: docs
weight: 10
---

## Grupos de trabalho
**Grupo 1**: Artur Abreu, Pedro Lemes, Arthur Joia e Gabriel Ramos

**Grupo 2**: Amanda Nascimento, Jancler Adrano, Lucas Gomes, Maria Júlia Alves e Naiara Caetano

**Grupo 3:** Amanda Evelyn, Aline Lacerda, Bárbara Silva e Isadora Oliveira

**Grupo 4:** Marina Caroline, Rayssa Aparecida, Thayna Assis e Yara Bertilie

**Grupo 5:** Arthus Ferraz, Mathias, Sebastião e Caroline

**Grupo 6:** Renata, Webert, Taynara e Leonardo

## Definição intuitiva sobre "LOGÍSTICA"
- Otimização de processos e métodos com o objetivo de reduzir custos e tempo e melhorar o produto ou serviço entregue.
- A logística possibilita levar qualquer coisa a qualquer lugar, de maneira a satisfazer os envolvidos.
- A logística é a análise e metodologias que levam em conta fatores terrestres, políticos, econômicos e tecnológicos para sua aplicação. 
- Logística é o modo de organizar e distribuir recursos a fim de otimizar o tempo e proporcionar qualidade dos processos.
- Gestão do processo produtivo que envolve o planejamento, armazenagem, mobilidade e rastreabilidade visando uma entrega de qualidade.
- Armazenamento e transporte de produtos e serviços visando a otimização de processos e a redução dos custos.

## Apresentação

```{r echo=FALSE, message=FALSE, warning=FALSE}
knitr::include_url('https://log2022.github.io/class01', height = "400px")
```

[LINK](https://log2022.github.io/class01)
