---
date: "2021-06-30T00:00:00+01:00"
draft: true
menu:
  log_epc:
    parent: Atividades de Aprendizagem
    weight: 11
title: 4. Gestão de transportes
editor_options: 
  markdown: 
    wrap: 70
output: 
  blogdown::html_page:
    toc: true
type: docs
weight: 45
---


O PRAZO DE ENTREGA DESTA ATIVIDADE PELO Dropbox Paper É: **04/07**

Leia do artigo [O uso da tecnologia nas adversidades da gestão de transportes](https://github.com/retaoliveira/relements/raw/main/texto/ti_transportes.pdf) e responda as perguntas no Dropbox Paper. 

1. Como as TICs podem contribuir para a mitigação dos impactos disruptivos e da pandemia COVID 19 na gestão de transportes?

2. Discuta o **problema estrutural** brasileiro quanto ao **transporte de cargas** em escala regional que compromete o alinhamento estratégico na cadeia de suprimentos, a eficiência, a responsividade, a sustentabilidade, a resiliência e a competitividade de produtos brasileiros no mercado internacional.

3. Na sua opinião, faz sentido os caminhoneiros demandarem intervenção das autoridades públicas para imposição de uma tabela de fretes mínimos ao mercado? Justifique. 
