---
date: "2020-12-275T00:00:00+01:00"
draft: true
menu:
  log_adm:
    parent: Atividades de aprendizagem
    weight: 5
title: 1. Logística e cadeia de suprimentos
editor_options: 
  markdown: 
    wrap: 70
output: 
  blogdown::html_page:
    toc: true
type: docs
weight: 20
---

## Objetivo de aprendizagem: 

Consolidar conceitos estruturais como "Logística" e "Cadeia de suprimentos". 

## Pontos

10 pontos

## Grupos de trabalho
**Grupo 1**: 

**Grupo 2**: 

**Grupo 3:** 

**Grupo 4:** 

**Grupo 5:** 

**Grupo 6:** 


## Atividades

Cada grupo deverá elaborar três perguntas objetivas sobre os conceitos "Logística" e "Cadeia de suprimentos". (10 minutos)

Essas perguntas serão distribuídas para os demais grupos para que todos elaborem uma resposta completa elaborada a partir do ChatGPT. Todas as perguntas feitas ao ChatGPT deverão ser inseridas ao fim da resposta elaborada pelo grupo. (10 minutos)

Posteriormente, cada grupo respondente ficará responsável pela revisão das perguntas respondidas e pela apresentação do que foi respondido e revisado. (5 minutos + apresentação)
