---
title: "Atividade 03"
draft: true
date: '2021-11-08T00:00:00+01:00'
menu:
  adm_prod:
    parent: Atividades avaliativas
    weight: 14
toc: yes
type: docs
weight: 14
---

1. O objetivo deste Planejamento é determinar os níveis dos recursos necessários para produzir a demanda esperada. Ou seja, determinar os níveis mensais de: mão-de-obra, produção, estoque. Este é o planejamento: 

a) De curto prazo   
b) Desmembrado   
c) De longo prazo   
d) Agregado   

2. No vídeo sobre Layout, faltou a explicação de um tipo muito comum em montadoras de veículos. 
É ele: 

a) Celular   
b) Posição Fixa   
c) Por processo   
d) Por produto   

3. Consiste em manter estacionado o produto a ser fabricado enquanto que matérias-primas, máquinas, equipamentos, recursos humanos são transportados até o mesmo. Este é o layout: 

a) Por posição fixa   
b) Por processo   
c) Por produto   
d) Celular   

4. Consiste em agrupar as máquinas e equipamentos de operações ou funções semelhantes em um mesmo espaço físico. Este é o layout: a) Por posição fixab) Por processoc) Por produtod) Celular5. Linhas de produção contínua onde o produto se locomove e as pessoas ficam estacionárias. Este é o layout: a) Por posição fixab) Por processoc) Por produtod) Celular6. Consiste em formar ´pequenas células que se constituem em mini-fábricas responsáveis pela produção completa de um produto ou componente de um produto maior. Este é o layout: a) Por posição fixab) Por processoc) Por produtod) Celular

7. A otimização do deste plano de Produção visa encontrar para cada mês os níveis de produção em hora regular e hora-extra/subcontratação, o nível de mão-de-obra empregada, e o nível dos estoques de modo a minimizar o custo total. Qual plano é este? a) Planejamento Agregado de Produçãob) Plano Mestre da Produçãoc) Plano Agregado de Produçãod) Planejamento de MRP8. O custo total da produção no Plano Agregado é calculado pela função: a) Custo de estoque + custo de produçãob) Custo fixo + custo variávelc) Custo + despesas fixas
d) Custo ABC + custo agregado + custo variável9. Estoque Zero = despreza os custos de produção e minimiza somente os estoques; Força de Trabalho Constante = calcula o nível de mão-de-obra para satisfazer as demandas no horizonte de planejamento e não a altera mais. Estas são estratégias de que tipo? a) Estratégias de estoque zero da produçãob) Estratégias constantes de produçãoc) Estratégia mescelar da produçãod) Estratégias radicais de produção10. Fazer-para-estoque é um tipo de planejamento em que algumas operações produzem bens ou serviços para estoque com antecedência em relação a qualquer pedido firme. Ex: alguns construtores vão construir casas ou apartamentos padrão pré-projetados antes de qualquer demandafirme. Nos sistemas de produção que vimos anteriormente, este se encaixa em: a) Sistema puxadob) Sistema just in timec) Sistema empurradod) Sistema Kanban11. Fazer-contra-pedido (make-to-order) - Um construtor de casas que tenha padronizado projetos pode optar por construir cada casa somente quando um consumidor tenha colocado um pedido firme. Devido ao fato de o projeto da casa ser relativamente padronizado, os fornecedores de materiais terão sido identificados, mesmo que a operação de construção não mantenha os itens em si em estoque. Este é um tipo de sistema de produção: a) Sistema puxadob) Sistema just in timec) Sistema empurradod) Sistema Kanban
