---
title: "Atividade preliminar"
draft: false
date: '2021-11-08T00:00:00+01:00'
menu:
  adm-prod:
    parent: Atividades avaliativas
    weight: 10
toc: yes
type: docs
weight: 10
---

Esta atividade deverá ser desenvolvida pelos grupos informados no trabalho de cronoanálise, a saber: 

Grupo 1: Caio Costa Rosa Santos, Rogério Pedersoli de Lima, Thais Paulo de Moura, Vanderlei Alves de Souza

Grupo 2: Pedro Henrique Figueiroa Mattos, Arthur Tertolino Manini e Erick Martins

Grupo 3: 

Grupo 4: 

Grupo 5: 

Os componentes do grupo deverão responder as perguntas que seguem apenas com o conhecimento adquirido ao longo desta disciplina, sem necessariamente consultar fontes formais para elaboração das respostas.

A entrega da atividade será realizada pela Tarefa no SIGAA 

1. Como as dimensões de (i) variedade do output, (ii) volume do output, (iii) variação da demanda, e (iv) visibilidade pelo consumidor diferenciam as decisões gerais da administração da produção?

2. Diferencie eficácia e eficiência/produtividade. Como esses dois conceitos se relacionam aos objetivos da administração da produção? 
