---
date: "2023-03-235T00:00:00+01:00"
draft: true
menu:
  adm_prod_mec:
    parent: Atividades de aprendizagem
    weight: 30
title: 3. Planejamento e controle de materiais
editor_options: 
  markdown: 
    wrap: 70
output: 
  blogdown::html_page:
    toc: true
    mathjax: default
type: docs
weight: 10
---

<script type="text/x-mathjax-config">
MathJax.Hub.Config({
  tex2jax: {
    skipTags: ['script', 'noscript', 'style', 'textarea', 'pre']
  }
});
</script>
<script async type="text/javascript"
  src="https://cdn.mathjax.org/mathjax/latest/MathJax.js?config=TeX-AMS-MML_HTMLorMML">
</script>


## **Atividade de aprendizagem**

### Gestão de Estoques

1. 	Uma empresa compra matéria-prima cinco vezes ao ano; o custo total anual de pedidos é $ 6.250,00. Qual o custo de cada pedido?

2.	A matéria-prima para fabricação de um produto é comprada de um fornecedor que entrega rapidamente seus pedidos. Sempre compram-se lotes de 200 unidades. O 
custo de cada pedido é $ 40,00 e o custo de armazenagem é de $ 5,00 por unidade, baseado no estoque médio. Se o consumo anual é de 30.000 peças com uma taxa constante, qual o custo total anual de estoque? 

3.	Uma empresa compra 10.000 peças por ano, para seu processo de montagem. Se o preço unitário for $ 8,00 e o custo de armazenagem de uma unidade anualmente equivale a 25% do valor de aquisição, o custo unitário de pedido for $ 200,00, qual será: 
a.	O lote econômico de compras
b.	O custo total ótimo
c.	O número de pedidos anuais
d.	O tempo entre pedidos

4.	A empresa alfa usa 30.000 unidades de uma matéria-prima por ano. O custo unitário do pedido é de $ 300,00, o custo de armazenagem é de $ 5,00 por unidade ao ano. O preço unitário é R$ 10,00. Calcule os valores das seguintes variáveis considerando lotes de compra de 30.000, 15.000, 5.000, 1.000 e 500 unidades: 
a.	O número anual de pedidos
b.	O custo anual de pedido
c.	O custo anual de armazenagem
d.	O custo total
Qual é o lote econômico de compras?
