---
date: "2023-08-07T00:00:00+01:00"
draft: false
menu:
  log_ta:
    parent: Atividades de Aprendizagem
    weight: 20
title: '04 - Dimensionamento de frotas'
editor_options: 
  markdown: 
    wrap: 70
output: 
  blogdown::html_page:
    toc: true
type: docs
weight: 20
---

1. Quantos veículos serão necessários para atender um cliente com as seguintes características referente ao fluxo de transportes:   

- Demanda: 50.000 toneladas/mês

- Imobilização média dos veículos: 10%

- Utilização média da disponibilidade dos veículos: 80%

- Ciclo dos veículos: 5 dias

- Capacidade nominal dos veículos: 80 toneladas-úteis

2. Uma empresa, proprietária de uma frota de veículos destinados ao transporte rodoviário, precisa calcular quantos veículos serão necessários para efetuar a movimentação de 100.000 toneladas-úteis de carga no período de um mês. 

Sabe-se que a imobilização de veículos é, em média, 10% da frota total e a utilização de veículos chega a 95% dos ativos disponíveis. Sabe-se ainda que o peso médio de cada veículo é 90% da capacidade nominal do veículo, de 27 toneladas. 

O tempo de ciclo para os veículos na rota entre os pontos A e B é equivalente a 4 dias. 

a)	Calcule o número de veículos necessários para a movimentação de toda a demanda de transporte no cenário proposto. 

b)	Se houvesse uma redução de um dia no ciclo, qual seria o impacto na necessidade de veículos. 

c)	Verifique a alteração da necessidade de veículos considerando um incremento no ciclo de meio dia, totalizando 4,5 dias, mas com aumento do carregamento de cada veículo para a capacidade nominal. 

3. Sabe-se que um cliente deseja transportar 50.000 toneladas por ano (365 dias por ano) de produtos siderúrgicos. Tem-se que, historicamente, o índice de imobilização dos caminhões equivale a 15% e o fator de utilização da disponibilidade dos veículos é de 85%. Sabe-se ainda que a capacidade nominal dos veículos é de 27 toneladas, e que o peso médio de carregamento totaliza 95% da capacidade nominal. O tempo de viagem no sentido carregado é de 36 horas. Já no sentido vazio, o tempo de viagem equivale a 30 horas. Os caminhões permanecem nos terminais para carga e descarga por 24 horas em cada terminal. Considera-se a frota da empresa para atendimento desse cliente, que totaliza 30 caminhões.

  a.	É possível atender o cliente? Justifique sua resposta de forma quantitativa. 
  
  b.	Assumindo que o valor de aquisição de cada caminhão seja R$ 200.000,00, vale à pena, sob o ponto de vista financeiro, investir R$ 500.000,00 em cada terminal visando a aquisição de novos equipamentos para carga e descarga com maior produtividade? Sabe-se ainda que, caso o investimento seja promovido, haverá redução de 12 horas na permanência dos caminhões em cada terminal. 

4.	Uma empresa de transporte rodoviário recebeu uma proposta de um potencial cliente para transportar 10.000 toneladas por mês de soja de um ponto de origem A, a um ponto de destino B, cuja distância é 500 km. Para oferecer o transporte desse produto, a empresa precisa saber quantos caminhões precisará alocar nesse fluxo de transporte.

Assume-se que o período de dimensionamento é equivalente a um mês (30 dias). Sabe-se ainda que a capacidade nominal de cada caminhão, adequado ao transporte de soja, é equivalente a 47 toneladas-úteis. Entretanto, devido à acomodação da carga no veículo, apenas 90% dessa capacidade é aproveitada. 

Sabe-se ainda que o tempo de deslocamento entre os pontos A e B é 8 horas, igual nos sentidos vazio e carregado. Os caminhões permanecem juntos aos clientes, em atividade de carga e descarga, por 5 horas em cada terminal. 

A manutenção dos caminhões tem apresentado um excelente desempenho, indicado pelo aumento de confiabilidade dos veículos e pela redução do tempo de permanência em manutenção, indicado pelo índice de imobilização, que é cerca de 10%. Entretanto, a utilização dos caminhões não está atendendo às expectativas dos gestores do processo de distribuição, atingindo um patamar de 20% dos veículos não utilizados.    
  a.	Dimensione as frotas de veículos para a movimentação de soja. 
  b.	Considerando que há 10 caminhões que podem ser alocados nesse fluxo, há gargalo operacional? 
  c.	Sugira um investimento que pode viabilizar a execução desse fluxo. Sugira ainda uma ação que pode gerar redução de custo operacional da empresa. 


