---
date: "2019-05-05T00:00:00+01:00"
draft: false
menu:
  log_especial:
    parent: Projetos
    weight: 1
title: Projeto Integrador
toc: true
type: docs
weight: 16
---

Esta atividade tem valor de 30 pontos e deverá ser entregue por meio do sigaa, na respectiva tarefa. Recomendo a elaboração de um documento contendo as etapas de elaboração do projeto.  

Você deverá:

1. **Registrar** alguma situação onde atividades-chave da cadeia de suprimentos acontecem e apresentam inadequações relacionadas a uma às duas dimensões: (i) eficiência - relação entre consumo dos recursos e a produção; (ii) responsividade - nível de serviço.

2. **Descrever** *brevemente* o fluxo (usando a imaginação mesmo!) desde um determinado fornecedor primário, passando pelas etapas de manufatura e pelas de distribuição até a situação registrada. Indique possíveis atividades depois do que é apresentado como registro considerando a estrutura da cadeia de suprimentos. 

3. **Relacionar** possíveis causas e soluções ao problema retratado.

4. **Discutir** as externalidades da operação retratada e como poderiam ser mitigadas, sem comprometer o _trade-off_ entre eficiência e responsividade. 

Seja completa e sucinta nas respostas! Ilustre bem o processo. Recomendo que escolha um processo familiar, pois fica mais fácil inferir sobre fluxos, causas e soluções.


