---
date: "2023-06-12T00:00:00+01:00"
draft: false
menu:
  log_adm:
    parent: Projetos
    weight: 65
title: Projeto Integrador 2
toc: true
type: docs
weight: 65
---

**Prazo para entrega: 07/07/2023**

Fiquem à vontade para utilizar a ferramenta que o grupo escolher. O envio será feito pela atividade aberta no SIGAA. Caso haja links, por favor, incluam no documento. O valor desta etapa é **20 pontos**.

Os grupos de trabalho deverão: 

1. **Registrar** alguma situação onde atividades-chave da cadeia de suprimentos acontecem e apresentam inadequações relacionadas à: (i) eficiência - relação entre consumo dos recursos e a produção; (ii) responsividade - nível de serviço.

2. **Caracterizar** os problemas relacionados à situação retratada - descrever, identificar elementos que compõe o processo...

3. **Determinar** possíveis impactos sobre as dimensões de sustentabilidade: (i) ambiental; (ii) social; (iii) econômico. 

4. **Escolher** uma das áreas de conhecimento da administração* e **relacionar** com as decisões em níveis estratégico e tático que são tomadas no dia-a-dia do profissional na área selecionada. 

*áreas de conhecimento da administração:   
- Humanidades   
- Jurídico.   
- Recursos Humanos.   
- Marketing ou Comercial.   
- Produção, Logística e Qualidade.   
- Econômico-Financeiro.   
- Estratégia / Empreendedorismo.   
- Gestao da informaçao.   
- Gestão de projetos.   

5. **Descrever** *brevemente* o fluxo (usando a imaginação mesmo!) desde um determinado fornecedor primário, passando pelas etapas de manufatura e de distribuição até a situação registrada. Indique possíveis atividades depois do que é apresentado como registro considerando a estrutura da cadeia de suprimentos. 

6. **Listar** possíveis causas do problema retratado.

7. **Discutir** como as externalidades da operação retratada poderiam ser mitigadas, sem comprometer o _trade-off_ entre eficiência e responsividade.

Sejam completos e sucintos nas respostas! Ilustrem bem o processo. Recomendo que escolham um processo familiar, pois fica mais fácil inferir sobre fluxos, causas e soluções. Registrem e adicionem fotos à apresentação e à ficha de registro. 
